basePath: /api/v1
definitions:
  models.CommonRabbitUser:
    properties:
      address:
        type: string
      user:
        type: string
    type: object
  models.Err:
    $ref: '#/definitions/models.Res'
  models.NewRabbitUser:
    properties:
      address:
        type: string
      pass:
        type: string
      user:
        type: string
    type: object
  models.Res:
    properties:
      code:
        type: integer
      msg:
        type: string
    type: object
  models.ServerDetail:
    properties:
      address:
        type: string
      name:
        type: string
      password:
        type: string
      port:
        type: integer
      username:
        type: string
    type: object
  models.ServersDetail:
    items:
      $ref: '#/definitions/models.ServerDetail'
    type: array
info:
  contact: {}
  description: 应用交付部署服务API
  license: {}
  title: 应用交付部署服务
  version: "1.0"
paths:
  /app/git/install:
    post:
      consumes:
      - application/json
      description: Git服务安装
      parameters:
      - description: server
        in: body
        name: server
        required: true
        schema:
          $ref: '#/definitions/models.ServerDetail'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Res'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Err'
      summary: Git服务安装
      tags:
      - Git服务
  /app/nfs/install:
    post:
      consumes:
      - application/json
      description: NFS服务安装
      parameters:
      - description: server
        in: body
        name: server
        required: true
        schema:
          $ref: '#/definitions/models.ServerDetail'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Res'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Err'
      summary: NFS服务安装
      tags:
      - NFS服务
  /app/rabbitmq/install:
    post:
      consumes:
      - application/json
      description: RabbitMQ服务安装
      parameters:
      - description: server
        in: body
        name: server
        required: true
        schema:
          $ref: '#/definitions/models.ServerDetail'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Res'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Err'
      summary: RabbitMQ服务安装
      tags:
      - RabbitMQ服务
  /app/rabbitmq/user/add:
    put:
      consumes:
      - application/json
      description: RabbitMQ用户添加
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.NewRabbitUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Res'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Err'
      summary: RabbitMQ用户添加
      tags:
      - RabbitMQ服务
  /app/rabbitmq/user/del:
    delete:
      consumes:
      - application/json
      description: RabbitMQ用户删除
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.CommonRabbitUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Res'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Err'
      summary: RabbitMQ用户删除
      tags:
      - RabbitMQ服务
  /app/rabbitmq/user/lst/{address}:
    get:
      consumes:
      - application/json
      description: RabbitMQ用户列表
      parameters:
      - description: address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Res'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Err'
      summary: RabbitMQ用户列表
      tags:
      - RabbitMQ服务
  /app/rabbitmq/vhost/add:
    put:
      consumes:
      - application/json
      description: RabbitMQ虚拟机添加
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.NewRabbitUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Res'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Err'
      summary: RabbitMQ虚拟机添加
      tags:
      - RabbitMQ服务
  /app/rabbitmq/vhost/del:
    delete:
      consumes:
      - application/json
      description: RabbitMQ虚拟机删除
      parameters:
      - description: server
        in: body
        name: server
        required: true
        schema:
          $ref: '#/definitions/models.ServerDetail'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Res'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Err'
      summary: RabbitMQ虚拟机删除
      tags:
      - RabbitMQ服务
  /app/rabbitmq/vhost/lst/{address}:
    get:
      consumes:
      - application/json
      description: RabbitMQ虚拟机列表
      parameters:
      - description: address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Res'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Err'
      summary: RabbitMQ虚拟机列表
      tags:
      - RabbitMQ服务
  /server/init:
    post:
      consumes:
      - application/json
      description: 单台服务器初始化
      parameters:
      - description: server
        in: body
        name: server
        required: true
        schema:
          $ref: '#/definitions/models.ServerDetail'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Res'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Err'
      summary: 单台服务器初始化
      tags:
      - 服务器
  /servers/init:
    post:
      consumes:
      - application/json
      description: 批量服务器初始化
      parameters:
      - description: servers
        in: body
        name: server
        required: true
        schema:
          $ref: '#/definitions/models.ServersDetail'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Res'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Err'
      summary: 批量服务器初始化
      tags:
      - 服务器
schemes:
- http
- https
swagger: "2.0"
